### ISSUE TITLE
This is not async

### ISSUE THREAD

**Issue by DiegoRBaquero** [semibran/async-map#1]
If you pass a long enough array. It will block the event-loop.

**Comment by semibran** [comment]
hi, mind giving an example? Pretty sure the underlying concept behind this module isn't much different than others used for similar purposes, callback shenanigans aside

**Comment by DiegoRBaquero** [comment]
Easy to see when: `map([...Array(5000).keys()], (v, cb) => cb(null, v*10), () => {})` will produce a Max call stack size exceeded.

If the iterate function is takes long, it would block the event-loop for long time.

**Comment by semibran** [comment]
thanks for the input. I made the tasks run in parallel and did a few tweaks so it should work now:+1:
